# @package _global_
defaults:
  - override /task: cartpole
  - override /policy: mlp_pi
  - override /solver: cem

task:
  harder: false
  
# policy:
#   hidden_dim: 128
# this only works for MLP_PI, not MLP. workaround is to hardcode in mlp.yaml
  
solver:
  pop_size: 128
  elite_size: 32
  stdev_init: 1.0

trainer:
  max_iter: 10000
  log_interval: 100
  test_interval: 1000
  n_repeats: 16
  n_evaluations: 100