# @package _global_
defaults:
  - override /task: mnist
  - override /policy: cnn
  - override /solver: pgpe
  
solver:
  pop_size: 64
  center_learning_rate: 0.006
  stdev_learning_rate: 0.089
  init_stdev: 0.039
  optimizer: adam

trainer:
  max_iter: 5000
  log_interval: 100
  test_interval: 1000
  n_repeats: 1
  n_evaluations: 1