defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

job:
  name: ${get_class_name:${task}}_${get_class_name:${solver}}
  config:
    override_dirname:
      exclude_keys:
        - run
        - mode
        - trainer.max_iter
  # env_set:
  #   CUDA_VISIBLE_DEVICES: ${hydra:job.num}

run:
  dir: output/${get_class_name:${task}}/${get_class_name:${solver}}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  subdir: ${hydra.job.override_dirname}

# job_logging:
#   formatters:
#     simple:
#       format: '[%(name)s][%(levelname)s] - %(message)s'
#     colorlog: 
#       format: '[%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
#   root:
#     level: WARNING
