defaults:
  - task: mnist
  - policy: cnn
  - solver: pgpe
  - trainer: trainer
  - hydra: base
  - wandb: disabled
  - run: mnist_pgpe # this changes task, policy, solver, trainer.*
  - mode: train # this changes trainer.max_iter and wandb.mode
  - _self_

seed: 42
gpu_id: 0